Citizen.CreateThread(function()
	AddTextEntry('WT_FAKEGNADE_SMK', 'Grenade Fumigène M18')
	AddTextEntry('WT_PELLE', 'Pelle')
	AddTextEntry('WT_CANETTE', 'Canette')
	AddTextEntry('WT_BOUTEILLE', 'Bouteille Cassé Jetable')
	AddTextEntry('WT_SLEDGEHAMMER', 'Masse')
	AddTextEntry('WT_PICKAXE', 'Pioche')
	AddTextEntry('WT_KATANA', 'Katana')
	AddTextEntry('WT_FAKESMG', 'MP5 non létale')
	AddTextEntry('WT_BEAMBAG', 'Bean bag')
	AddTextEntry('WT_CHAINSAW', 'Tronçonneuse')
	AddTextEntry('WT_NAILGUN', 'Pistolet à clou')
end)